CREATE DATABASE [OurFisrtDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OurFisrtDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\OurFisrtDatabase.mdf' , SIZE = 65536KB , MAXSIZE = 1048576KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'OurFisrtDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\OurFisrtDatabase_log.ldf' , SIZE = 32768KB , MAXSIZE = 524288KB , FILEGROWTH = 65536KB )
 WITH LEDGER = OFF
GO
ALTER DATABASE [OurFisrtDatabase] SET COMPATIBILITY_LEVEL = 160
GO
ALTER DATABASE [OurFisrtDatabase] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET ARITHABORT OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [OurFisrtDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [OurFisrtDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [OurFisrtDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET  DISABLE_BROKER 
GO
ALTER DATABASE [OurFisrtDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [OurFisrtDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [OurFisrtDatabase] SET  READ_WRITE 
GO
ALTER DATABASE [OurFisrtDatabase] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [OurFisrtDatabase] SET  MULTI_USER 
GO
ALTER DATABASE [OurFisrtDatabase] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [OurFisrtDatabase] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [OurFisrtDatabase] SET DELAYED_DURABILITY = DISABLED 
GO
USE [OurFisrtDatabase]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [OurFisrtDatabase] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO